Feature/debounce button
project-march/ethercat-slaves pull request #43
Opened 2020-05-08 09:16 UTC by JeftaJochem

## Description
In order to protect the hardware it is essential to debounce all inputs to the mbed. For now, only the emergency button is debounced. But the Class that was created can be used for any future mechanical input (button) that will be connected to the mbed. The on/off could be debounced later, this could be an issue for later. 

The emergency button was the top priority for this PR. A bouncing emergency button could rapidly switch the MOSFETs on and off and destroy them.  Also it is good practice to use debouncing on every mechanical input on any device. The debounce time [us] can be changed in the constructor, but for now the debounce time is set at one second(1000000 us). 

The software was successfully tested on an mbed.

## Changes
- Added button.cpp and Button.h
- Added debounceRead function in while loop of main.cpp of pdb
- Renamed `button` to `onOffButton`
- Changed `wait_ms()` to `wait_us()`

2020-05-08 09:38 UTC, Olavhaasie reviewed
Congrats on your first contribution :tada: Everythings seems ok, except for the code style. Fortunately, you can do this automatically. If you are using VS code, you can enable `Format on Save` in the settings. Finally, you have to fix the `src/pdb/main.cpp` and `src/standalone_pdb/main.cpp` files by using the `Control + Shift + I` key shortcut and then committing the changes.

Let me know if you need any more help :hand:

2020-05-08 13:01 UTC, bjornminderman requested changes
You've done it, your first PR! Overall it is looking very good. You might, however, also want to consider to alter the `standalone_pdb` environment in the same way you altered the `pdb` environment, since we might not switch to the PDB with EtherCAT in the very near future. Further (besides some small comments) nice job!

2020-05-11 19:33 UTC, JorisWeeda commented on lib/button/Button.cpp
> +  if (initialButton != readValue && this->debounceTimer.read_us() == 0)  // Is the button in the same state? has it
Could be! The code is highly intuitive so maybe just delete the comments, your call! :1st_place_medal:

2020-05-11 19:40 UTC, Joris-JW reviewed
Nice work!! :100:  As earlier suggested the coding style is a bit out of place but easy to fix with Olav his tips. As Bjorn requested the comments have to be checked again. In my opinion the code is nice and readable so the comments can maybe just be delete or, as we do in the hardware interface, do a general comment per function. Anyway, that's your call!

2020-05-11 19:42 UTC, JorisWeeda commented on lib/StateMachine/StateMachine.cpp
>    int ledTimeMs = this->ledTimer.read_ms();
I would change these to ```read_us()``` to keep consistency.

2020-05-14 12:08 UTC, JeftaJochem commented on lib/button/Button.cpp
> +  if (initialButton != readValue && this->debounceTimer.read_us() == 0)  // Is the button in the same state? has it
I have added new comments, however I code is intuitive enough without comments.

2020-05-27 12:22 UTC, Olavhaasie commented
@bjornminderman reminder :bell: some changes were made since your last review, so could you please take a look

2020-05-29 09:59 UTC, bjornminderman requested changes
Almost there, just a few little naming issues to tackle

2020-05-29 09:59 UTC, bjornminderman commented on src/pdb/main.cpp
> +    bool onOffButtonstate = onOffbutton.read();
I would change `onOffButtonstate` to `onOffButtonState` for consistency reasons. Also the build fails on `onOffbutton.read()` which should be changed to `onOffButton.read()` 

```suggestion
    bool onOffButtonState = onOffButton.read();
```

2020-05-29 09:59 UTC, bjornminderman commented on src/pdb/main.cpp
> +    stateMachine.updateState(onOffButtonstate, masterOnline, (bool)mosi.masterShutdownAllowed);
```suggestion
    stateMachine.updateState(onOffButtonState, masterOnline, (bool)mosi.masterShutdownAllowed);
```

2020-05-29 09:59 UTC, bjornminderman commented on src/standalone_pdb/main.cpp
> +DigitalIn button(LPC_ONOFFBUTTON_PRESSED, PullDown);  // True means button pressed
Maybe you can change this to onOffButton, just like you did for the PDB with EtherCAT. Don't forget to change this throuhout the entire file.

```suggestion
DigitalIn onOffButton(LPC_ONOFFBUTTON_PRESSED, PullDown);  // True means button pressed
```

2020-05-29 10:18 UTC, bjornminderman requested changes

2020-05-29 10:18 UTC, bjornminderman commented on src/standalone_pdb/main.cpp
> +    stateMachine.updateState(OnOffbuttonState, true, false);
```suggestion
    stateMachine.updateState(OnOffButtonState, true, false);
```

2020-06-01 09:14 UTC, Olavhaasie approved these changes
@bjornminderman If you could take a final look :innocent:

2020-06-02 07:54 UTC, bjornminderman approved these changes

2020-06-02 07:55 UTC, merged